### ISSUE TITLE
Licence Terms

### ISSUE THREAD

**Issue by Mdyunus56** [shail9689/ng-lz-string#12]
Hi Shailendra,

Thanks for the Package, can we use this package in any personal, non-commercial, commercial application? looking for license terms. It will be helpful if tag it under some open source license (MIT, Apache etc.) if applicable.

Regards,
Md Yunus

**Comment by shailendragusain** [comment]
Hi @Mdyunus56,

The licence is now attached.
Apologies I was not actively working on this repo.
